/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { z } from "zod";
import { shippingAddressSchema } from "./shipping-address.js";

export const paymentMandateSchema = z.object({
  paymentMandateContents: z.object({
    paymentMandateId: z
      .string()
      .describe("A unique identifier for this payment mandate."),
    paymentDetailsId: z
      .string()
      .describe("A unique identifier for the payment request."),
    paymentDetailsTotal: z
      .object({
        label: z.string().describe("A human-readable description of the item."),
        amount: z.object({
          currency: z
            .string()
            .describe("The three-letter ISO 4217 currency code."),
          value: z.number().describe("The monetary value."),
        }),
        pending: z
          .boolean()
          .optional()
          .describe("If true, indicates the amount is not final."),
        refundPeriod: z
          .number()
          .default(30)
          .describe("The refund duration for this item, in days."),
      })
      .describe("The total payment amount."),
    paymentResponse: z
      .object({
        requestId: z
          .string()
          .describe("The unique ID from the original PaymentRequest."),
        methodName: z
          .string()
          .describe("The payment method chosen by the user."),
        details: z
          .record(z.string(), z.unknown())
          .optional()
          .describe(
            "A dictionary generated by a payment method that a merchant can use to process a transaction."
          ),
        shippingAddress: shippingAddressSchema.optional(),
        shippingOption: z
          .object({
            id: z.string(),
            label: z.string(),
            amount: z.object({
              currency: z.string(),
              value: z.number(),
            }),
            selected: z.boolean().optional(),
          })
          .optional(),
        payerName: z.string().optional(),
        payerEmail: z.string().optional(),
        payerPhone: z.string().optional(),
      })
      .describe(
        "The payment response containing details of the payment method chosen by the user."
      ),
    merchantAgent: z.string().describe("Identifier for the merchant."),
    timestamp: z
      .string()
      .describe(
        "The date and time the mandate was created, in ISO 8601 format."
      ),
  }),
  userAuthorization: z
    .string()
    .optional()
    .describe(
      "A base64url-encoded verifiable presentation signing over the cart and payment mandate hashes."
    ),
});
