"""Credential Provider MCP Server.

Mandate verification and payment token management.

Exposes two MCP tools consumed by the ADK shopping agent over stdio:
  issue_payment_credential, revoke_payment_credential.

Mandate verification (SD-JWT signature + chain checks) happens internally
inside ``issue_payment_credential`` before a payment token is issued.
"""

import json
import logging
import os
import time
import uuid

from collections.abc import Mapping
from pathlib import Path
from typing import Any

from ap2.sdk.mandate import MandateClient
from ap2.sdk.payment_mandate_chain import PaymentMandateChain
from ap2.sdk.receipt_wrapper import ReceiptClient
from ap2.sdk.utils import compute_sha256_b64url
from common.constants import (
  AGENT_PROVIDER_PUB_PATH,
  MERCHANT_PAYMENT_PROCESSOR_PUB_PATH,
  TEMP_DB,
)
from fastmcp import FastMCP
from fastmcp.server.middleware.logging import LoggingMiddleware
from jwcrypto.jwk import JWK


mcp = FastMCP("Credential Provider MCP Server")

_SCRIPT_DIR = Path(__file__).resolve().parent
_LOG_DIR = Path(os.environ.get("LOGS_DIR", _SCRIPT_DIR.parent / ".logs"))
_LOG_FILE = _LOG_DIR / "credential-provider-mcp.log"
_LOG_DIR.mkdir(parents=True, exist_ok=True)
_logger = logging.getLogger("credential-provider-mcp")
_logger.setLevel(logging.INFO)
_handler = logging.FileHandler(_LOG_FILE, mode="w", encoding="utf-8")
_handler.setFormatter(
    logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
)
_logger.addHandler(_handler)

mcp.add_middleware(
    LoggingMiddleware(
        logger=_logger,
        include_payloads=True,
        include_payload_length=True,
        max_payload_length=8000,
    )
)

_TOKEN_STORE_PATH = Path(
    os.environ.get(
        "AP2_TOKEN_STORE_PATH",
        str(TEMP_DB / "ap2_token_store.json"),
    )
)

_TOKEN_EXPIRY_SECONDS = 300


def _load_token_store() -> dict[str, Any]:
  try:
    with open(_TOKEN_STORE_PATH) as f:
      return json.load(f)
  except FileNotFoundError:
    return {}
  except (json.JSONDecodeError, OSError):
    _logger.warning("token_store load failed", exc_info=True)
  return {}


def _save_token_store(store: dict[str, Any]) -> None:
  try:
    _TOKEN_STORE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(_TOKEN_STORE_PATH, "w") as f:
      json.dump(store, f, indent=2)
  except OSError:
    _logger.exception("token_store save failed")


def _get_agent_provider_public_key() -> JWK | None:
  """Loads the Agent Provider's public JWK from a file."""
  try:
    if AGENT_PROVIDER_PUB_PATH.exists():
      return JWK.from_json(AGENT_PROVIDER_PUB_PATH.read_text(encoding="utf-8"))
  except (ValueError, json.JSONDecodeError, OSError) as e:
    _logger.warning("could not load agent-provider public key: %s", e)
  return None


def _get_merchant_payment_processor_public_key() -> JWK | None:
  """Loads the merchant payment processor public key from disk as JWK."""
  try:
    if MERCHANT_PAYMENT_PROCESSOR_PUB_PATH.exists():
      return JWK.from_json(
          MERCHANT_PAYMENT_PROCESSOR_PUB_PATH.read_text(encoding="utf-8")
      )
  except (ValueError, json.JSONDecodeError, OSError) as e:
    _logger.warning(
        "could not load merchant payment processor public key: %s", e
    )
  return None


def _load_persisted_mandate(filename: str) -> str | None:
  """Read an SD-JWT written by the agent's mandate tools."""
  path = TEMP_DB / filename
  try:
    return path.read_text(encoding="ascii").strip()
  except FileNotFoundError:
    return None
  except OSError:
    _logger.exception("Could not load persisted mandate %s", filename)
  return None


@mcp.tool()
def issue_payment_credential(
    payment_mandate_chain_id: str,
    open_checkout_hash: str,
    checkout_jwt_hash: str,
    payment_nonce: str,
) -> Mapping[str, Any]:
  """Verify the mandate chain, then issue a scoped single-use payment token.

  Internally:
    1. Verify the SD-JWT delegation chain (open -> closed via cnf).
    2. Check the closed mandate satisfies the open mandate constraints.
    3. Issue a token bound to the mandate chain.

  Args:
      payment_mandate_chain_id: The combined open and closed payment mandate
        SD-JWTs separated by '~~', or a mandate chain ID (e.g., 'pay_...').
      open_checkout_hash: base64url SHA-256 of the open checkout mandate.
      checkout_jwt_hash: base64url SHA-256 of the checkout JWT.
      payment_nonce: The nonce generated by the Shopping Agent when creating
        the payment mandate presentation.

  Returns:
      ``payment_token`` and ``expires_at`` on success,
      or an ``error`` dict on failure.
  """
  _logger.info("issue_payment_credential called")

  payment_mandate_chain = None
  if payment_mandate_chain_id:
    payment_mandate_chain = _load_persisted_mandate(
        f"{payment_mandate_chain_id}.sdjwt"
    )

  if not payment_mandate_chain:
    return {
        "error": "mandate_not_found",
        "message": (
            "Could not load payment_mandate from"
            f" {payment_mandate_chain_id}.sdjwt"
        ),
    }

  try:
    if not open_checkout_hash:
      return {
          "error": "missing_fields",
          "message": "open_checkout_hash is required",
      }
    if not checkout_jwt_hash:
      return {
          "error": "missing_fields",
          "message": "checkout_jwt_hash is required",
      }
    if not payment_nonce:
      return {
          "error": "missing_fields",
          "message": "payment_nonce is required",
      }

    agent_provider_pub = _get_agent_provider_public_key()
    if not agent_provider_pub:
      return {"error": "agent_provider_key_not_found"}

    try:
      payloads = MandateClient().verify(
          token=payment_mandate_chain,
          key_or_provider=lambda _token: agent_provider_pub,
          expected_aud="credential-provider",
          expected_nonce=payment_nonce,
      )
      chain = PaymentMandateChain.parse(payloads)
      violations = chain.verify(
          expected_open_checkout_hash=open_checkout_hash,
          expected_transaction_id=checkout_jwt_hash,
      )
    except (ValueError, TypeError) as e:
      _logger.exception("issue_payment_credential: mandate verification failed")
      return {
          "error": "verification_failed",
          "message": f"mandate verification failed: {e}",
      }

    if violations:
      _logger.warning(
          "issue_payment_credential: constraint violations: %s", violations
      )
      return {
          "error": "verification_failed",
          "message": "; ".join(violations),
      }

    token = "tok_" + str(uuid.uuid4()).replace("-", "")
    reference = compute_sha256_b64url(
        MandateClient().get_closed_mandate_jwt(payment_mandate_chain)
    )
    expires_at = int(time.time()) + _TOKEN_EXPIRY_SECONDS
    token_data = {
        "token": token,
        "reference": reference,
        "payment_mandate_chain": payment_mandate_chain,
        "payment_nonce": payment_nonce,
        "used": False,
        "expires_at": expires_at,
    }

    # Store the token data with both the token and the reference as keys.
    store = _load_token_store()
    store.update(
        dict.fromkeys(
            [
                token,
                reference,
            ],
            token_data,
        )
    )
    _save_token_store(store)

    _logger.info("issue_payment_credential result: token=%s...", token[:16])
    return {
        "payment_token": token,
        "expires_at": expires_at,
    }
  except Exception as e:  # pylint: disable=broad-exception-caught
    _logger.exception(
        "CRITICAL: issue_payment_credential failed with unexpected error"
    )
    return {"error": "unexpected_error", "message": str(e)}


@mcp.tool()
def revoke_payment_credential(payment_token: str) -> Mapping[str, Any]:
  """Revoke a previously issued payment token."""
  _logger.info(
      "revoke_payment_credential called: payment_token=%s...",
      payment_token[:12] if payment_token else "None",
  )
  if not payment_token:
    return {"revoked": False, "error": "missing_payment_token"}
  store = _load_token_store()
  if payment_token in store:
    del store[payment_token]
    _save_token_store(store)
    _logger.info("revoke_payment_credential result: revoked=True")
    return {"revoked": True}
  _logger.warning("revoke_payment_credential result: token_not_found")
  return {"revoked": False, "error": "token_not_found"}


@mcp.tool()
def verify_payment_receipt(payment_receipt: str) -> Mapping[str, Any]:
  """Verify a payment receipt from the merchant payment processor.

  Args:
      payment_receipt: The payment receipt JWT to verify.

  Returns:
      A dictionary with the verification result.
  """
  _logger.info(
      "verify_payment_receipt called: payment_receipt=%s...", payment_receipt
  )

  mpp_pub = _get_merchant_payment_processor_public_key()
  if not mpp_pub:
    return {"error": "merchant_payment_processor_public_key_not_found"}

  result = ReceiptClient().verify_receipt(
      receipt_jwt=payment_receipt,
      receipt_issuer_public_key=mpp_pub,
      has_reference_in_store_cb=lambda reference: reference
      in _load_token_store(),
      is_payment_receipt=True,
  )
  _logger.info(
      "verify_payment_receipt result: %s",
      result,
  )

  if "error" in result:
    return result

  return {"verified": True}


if __name__ == "__main__":
  mcp.run()
